### ISSUE TITLE
Add shoreline mapping functionality to 'SDS_unet_classifier'

### ISSUE THREAD

**Issue by dbuscombe-usgs** [SatelliteShorelines/CoastSeg#101]
_Overview_
'SDS_unet_classifier' now appears to work well at presenting options to the user, downloading and applying models to images to create 'predseg' label image outputs

The final step is to extract and the shorelines using the `SDS_shoreline.py` functionality. It needs a workflow similar to the `SDS_coastsat_classifier` which involves a `Extract shorelines' step, followed by  a 'compute transects', and finally a 'save transects csv' file

The final outputs from the `SDS_unet_classifier` should be the same as `SDS_coastsat_classifier` so they can be compared

_Specifics_

A new `SDS_shoreline.py/extract_shorelines` version is needed, in which `classify_image_NN` is not called (it is not needed), instead using the Zoo model output instead of the CoastSat classifier

Or perhaps it  is much easier to create a new version of `classify_image_NN` function that works with a Zoo model. Conceptually, this seems to be simpler. It would take the settings from the user (imagery type, model, TTA, Otsu, etc) and pass them to a function like `classify_image_NN` that would output `im_classif` and `im_labels` variables

**Comment by 2320sharon** [comment]
- [ ] Isolate call to `classify_image_NN` in `SDS_shoreline.py/extract_shorelines` and find what inputs it requires
- [ ]  Figure out how current  `classify_image_NN` functions
- [ ]override `SDS_shoreline.extract_shorelines`  with our own extract shorelines or find a better approach

**Comment by 2320sharon** [comment]
I did some digging into how SDS_shorelines.extract_shorelines and classify_image_NN works to prep for our meeting today.

Basically SDS_shorelines.extractshorelines() creates a reference shoreline mask which is a Boolean pixel level np.array  that has true values where the reference shoreline is in the image. The reference shoreline mask is used with the outputs of the classifiy image NN() outputs to find the shoreline within the image using one of the find_wl_contours functions. The classifiy image NN() makes two outputs but only one output, imlabels , is relevant to us since the   find_wl_contours uses it to find the shorelines within the image. imlabels is an stacked np.array of booleans. It has 4 layers:
    Classifies every pixel in the image in one of 4 classes:
        - sand                                          --> label = 1
        - whitewater (breaking waves and swash)         --> label = 2
        - water                                         --> label = 3
        - other (vegetation, buildings, rocks...)       --> label = 0
Of these layers the only important ones that are actually used are sand, whitewater, and water as these are used by find_wl_contours .

For whatever model we choose to use it must output the following classes at a minimum: sand, whitewater, and water so that it can work natively with the built in find_wl_contours from CoastSat. It shouldn't be too hard to convert the outputs of our models into a similar format to the imlabels that the classifiy image NN()  outputs.

Due to the fact that  SDS_shorelines.extract_shorelines loads in Killian's models and performs other preprocessing that won't be relevant to our purposes I believe the best course of action is to create our own version of extract shorelines. We can create this new function either in coastseg or coastsat. I think it should remain in coastseg, but we should ask Killian if he would like it ported to coastsat as a new function.

I'll post this on the github issue as well, but I wanted to put this here so we are on the same page during the meeting today. Thanks for reading this long post:smiley:

**Comment by 2320sharon** [comment]
This has been added to coastseg and future updates will improve the extract shorelines functionaliy.
