### ISSUE TITLE
Examples folder contains data 

### ISSUE THREAD

**Issue by FlorisCalkoen** [SatelliteShorelines/CoastSeg#246]
ping #openjournals/joss-reviews#6683

I expected to find notebooks in the [examples](https://github.com/SatelliteShorelines/CoastSeg/tree/main/examples) directory, but there is data. I would suggest rename this to data. 

Moreover, I would try to avoid contaminating the repository with any data. I think it's better to keep storage and code seperated. Adding data to GH repo's can make them tedious and frustrating to work with. I might consider opening a separate issue on this.

**Comment by 2320sharon** [comment]
Hi Floris,

I understand the concern about having data in the repository. The only data we have included currently is the default transects data and the example geojson files you pointed out that are used in the `1_download_imagery.py` script, which we have a short guide on at [CoastSeg website](https://satelliteshorelines.github.io/CoastSeg/CoastSeg-API-Guide/#script-1-download-imagery-and-initial-shoreline-extraction). To make things a bit easier for a new user we could add a txt file to the `examples` folder to explain this data is used for the demo scripts, but plenty of other tools include a small amount of demo data for their examples as well.

As for the default transect data we provide having it provided with the CoastSeg project makes it so that users don't need to wait to download transect data and that we don't have to worry about breaking any links if we decide to modify the default transects available to CoastSeg.

**Comment by 2320sharon** [comment]
@FlorisCalkoen 

I understand the confusion regarding the 'examples' directory. Originally I wanted to put our example scripts `1_download_imagery.py` and `2_extract_shorlines.py` in that folder, but doing so caused errors because the underlying coastsat code expects the `/data` to be at the same level as the script running. 

Thank you for the suggestion to use [pooch](https://github.com/fatiando/pooch) we might consider using pooch to download the default transects and shorelines at some point so that the code to download the data won't need to be coded into coastseg.

**Comment by dbuscombe-usgs** [comment]
We're talking about 32.3 kB of data, in just 4 files, that are named unambiguously.

Pooch is a fine idea for larger data files, but I personally don't think it is worth the extra dependency. What happens when pooch is no longer maintained? Also, why is python 3.11 hard-coded into their [requirements.yml](https://github.com/fatiando/pooch/blob/main/environment.yml)?

**Comment by 2320sharon** [comment]
@FlorisCalkoen Thank you for the suggestion to use a `configure_instance()` function that would solve a few of the problems we've been faced before. If you could open a PR with that code that would be awesome.
