### ISSUE TITLE
Would it be possible to run the UI in the browser outside Jupyter? 

### ISSUE THREAD

**Issue by FlorisCalkoen** [SatelliteShorelines/CoastSeg#252]
ping #openjournals/joss-reviews#6683

So far I have been mapping shorelines using the example notebooks in a JupyterLab IDE. This works, but sometimes searching for right settings becomes a bit tedious because the UI is relatively small in a Jupyter NB. You may consider running the UI in a web server instead of interacting with it through Jupyter. You could put the underlying code in a script that you launch through a CLI, e.g., `mamba activate coastseg; coastseg start` or `mamba activate coastseg; python -m coastseg main.py`. You may find some inspiration [here](https://panel.holoviz.org/gallery/)  - not necessasrily saying that you should port your code to holoviews, but it might give you a good idea on what's currently possible!

**Comment by 2320sharon** [comment]
Hey @FlorisCalkoen we ran into a similar issue where some of our super users like @mlundine,  who are using CoastSeg on a few hundred sites, were finding that adjusting the settings manually was time-consuming. To make things faster we developed CoastSeg API to enable your own scripting, i.e., 'headless mode', which we have a tutorial on [here](https://satelliteshorelines.github.io/CoastSeg/CoastSeg-API-Guide/). Basically this lets you run CoastSeg as a script which makes testing settings much faster.

Thanks for your question as to why CoastSeg is not a dedicated web server application instead of a Jupyter instance. Early on we explored turning CoastSeg into a Holoviews application and one of our team members at the time worked on developing an [application](https://github.com/venuswku/data-visualizer) using Holoviews to visualize geospatial data. She ran into significant  performance issues rendering items on the map efficiently, difficulty creating custom components, and each of these issues took weeks to months to fix. The difficulty of developing with this software made us decide to stick with Jupyter as it is easy to customize, add new features to, and almost everyone already knows how to use. Moreover, and most importantly, as we state repeatedly in the paper, the community are encouraged to contribute notebooks to CoastSeg and add new features, hence we want to keep the Jupyter interface that makes this easy to do. We strongly feel Jupyter is widely accessible and familiar, so we plan to stick with it for the foreseeable.

**Comment by FlorisCalkoen** [comment]
Hi @2320sharon, many for your extensive answer and those scripts should indeed help a lot when doing a more extensive search towards finding the right settings. Please don't take all my issues as "these have to be addressed"; I'm following JOSS guidelines in opening issues for every thing I come accross as they have found that to be the most constructive way of working towards better software. I fully understand you don't want to port the whole thing to Holoviews! Do you know what performance issues you encountered before with Holoviews? Because I typically use Holoviews for big-data visualization (although the datashader makes working with geospatial features more difficult at an item level).

**Comment by dbuscombe-usgs** [comment]
Seems like this can be closed.
