### ISSUE TITLE
In SDS_zoo_classifier.ipynb the instructions and default settings are inconsistent

### ISSUE THREAD

**Issue by FlorisCalkoen** [SatelliteShorelines/CoastSeg#253]
ping #openjournals/joss-reviews#6683

Just a small enhancement. In the SDS_zoo_classifier.ipynb you recommend in the introduction to use ensemble as the model, but this setting is actually hidden under the advanced settings, where `BEST` is the default setting. I recommend either changing the recommendation to `BEST` or change the default value to `ENSEMBLE`

<img width="1113" alt="Screenshot 2024-05-21 at 12 24 00 PM" src="https://github.com/SatelliteShorelines/CoastSeg/assets/44444001/7620e6f5-d0cc-466b-b90a-51fa54400998">

**Comment by dbuscombe-usgs** [comment]
@2320sharon I suggest removing the recommendation to use ENSEMBLE model, by removing "(Ensemble is recommended because it uses multiple models to create more accurate predictions)." from the preamble. We don't want to be overly prescriptive until the benchmark paper is out

**Comment by 2320sharon** [comment]
@dbuscombe-usgs I'm updating it now. It should be alright to recommend Best for now because it runs a bit faster than ensemble right?

**Comment by dbuscombe-usgs** [comment]
Sure, or just leave it blank and allow users to discover what works for them. It's easy enough to do, just make a new session ...

**Comment by 2320sharon** [comment]
I decided to give the zoo notebook an update while I changed the recommended model from ENSEMBLE to BEST. Below is the new instructions for the zoo notebook

Thanks for catching this @FlorisCalkoen 

## How to Run Image Segmentation Models on the Downloaded Imagery
---

1. **Select Imagery Type**: Choose the type of imagery you have: **RGB**, **NDWI**, or **MNDWI**.
   - If you select **NDWI** or **MNDWI**, the **RGB** directory will automatically be converted to the selected type and saved to a new folder named after the selected type. For example, if you choose **NDWI**, a new directory called **NDWI** will appear next to the **RGB** directory.

2. **Choose a Model**: Select the image segmentation model you want to use.

3. **Select Performance Mode**: Choose between **Ensemble** or **Best** (Best is recommended for faster performance).
   - **Best**: Uses only the best model available on the images. This option is faster since it involves a single model making the prediction.
   - **Ensemble**: Utilizes all available models to create more accurate predictions. Although it takes longer to make a single prediction, the resulting segmentation is generally more accurate.


4. **Select Imagery Directory**: Choose the directory of imagery to run the model on.
   - Select an ROI (Region of Interest) directory under the `data` directory.
   - Always select a directory named 'RGB'.


## Need More Help?

Check out the CoastSeg website: [CoastSeg Models](https://satelliteshorelines.github.io/CoastSeg/models/)

**Comment by 2320sharon** [comment]
The notebook has been updated with the newest instructions posted here. Closing the issue
